# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-11 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='job_title',
            new_name='address',
        ),
    ]
