# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-11 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180411_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='location',
            new_name='city',
        ),
    ]
